### ISSUE TITLE
entrypoint.sh generating of keys

### ISSUE THREAD

**Issue by frphu** [microservices-today/ngp-airflow#2]
the generation of the fernet key and the secret key should only happen once and be uniform between all the containers.

Fernet key is used to encrypt and store passwords in the database so having it generated each time a container starts won't work.

Secret key is used by the flask app to sign cookies I believe

**Comment by frphu** [comment]
Instead maybe not generate the keys and provide instructions in readme for users to generate the keys

**Comment by neethugeorge** [comment]
Removed keys from `entrypoint.sh` , provided instructions in readme for users to generate keys.
Resolved by #4
